name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Replace with your default branch if not 'main'

permissions:
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install dependencies, build and run unit tests
        run: |
          cd client
          npm install
          npm run test
          npm run build
        

      - name: Upload build artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          name: build
          path: client/build/

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: build
          path: client/build/

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact_name: build

