name: Discord Notification on Commit

on:
  push:
    branches:
      - main  # Replace 'main' with the name of your base branch

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16  # Set the Node.js version here to Node.js 16

      - name: Install dependencies
        run: npm install discord.js

<<<<<<< HEAD
      - name: Send Discord Notification on Pull Request
        run: |
          const { WebhookClient, MessageEmbed } = require('discord.js');
=======
      - name: Send Discord Notification on Commit
        run: |
          node - <<EOF
            const { WebhookClient, MessageEmbed } = require('discord.js');
>>>>>>> test-workflow

            const webhook = new WebhookClient({
              url: process.env.DISCORD_WEBHOOK_URL,
            });

<<<<<<< HEAD
          const mention = process.env.DISCORD_MENTION || '';
          const pr = process.env.GITHUB_EVENT_PATH;

          try {
            const prData = require(pr);

            if (prData && prData.pull_request && prData.pull_request.user && prData.pull_request.user.login) {
              const embed = new MessageEmbed()
                .setColor('#0099ff')
                .setTitle('New Pull Request Created')
                .setDescription(`A new pull request has been created by ${prData.pull_request.user.login}`)
                .addField('Title', prData.pull_request.title, true)
                .addField('Repository', prData.repository.full_name, true)
                .addField('Branch', prData.pull_request.head.ref, true)
                .addField('Reviewers', mention, true)
                .setTimestamp();

              webhook.send({ embeds: [embed] });
            } else {
              console.error('Error: Missing or invalid data in prData');
            }
          } catch (error) {
            console.error('Error:', error);
          }
=======
            const commit = process.env.GITHUB_SHA.substring(0, 7);
            const repoName = process.env.GITHUB_REPOSITORY;
            const branchName = process.env.GITHUB_REF.replace('refs/heads/', '');

            const embed = new MessageEmbed()
              .setColor('#0099ff')
              .setTitle('New Commit')
              .setDescription(`A new commit has been made to the branch ${branchName} in ${repoName}.`)
              .addField('Commit', commit, true)
              .setTimestamp();

            webhook.send({ embeds: [embed] });
          EOF
>>>>>>> test-workflow
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
