name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Replace with your default branch if not "main"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Git user information
        run: |
          git config user.email "thaihayden@gmail.com"
          git config user.name "Hayden Thai"

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install Dependencies
        run: npm install
        working-directory: ./client  # Navigate to your React app folder

      - name: Build & Deploy
        run: |
          npm run build
          npm run deploy
        working-directory: ./client  # Navigate to your React app folder
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
