name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Replace with your default branch if not "main"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Change Directory
        run: cd client  # Navigate to your React app folder

      - name: Install Dependencies
        run: npm install

      - name: Build & Deploy
        run: |
          npm run build
          npm run deploy
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
