name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Replace with your default branch if not 'main'
      - 10-stretch-goal-create-github-workflowdeploy-front-end-github-pages  # Additional branch

permissions:
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install dependencies and build
        run: |
          cd client
          npm install
          echo "REACT_APP_SPOONACULAR_API_KEY=${{ secrets.REACT_APP_SPOONACULAR_API_KEY }}" > .env.production
          npm run build
        env:
          REACT_APP_SPOONACULAR_API_KEY: ${{ secrets.REACT_APP_SPOONACULAR_API_KEY }}

      - name: Upload build artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          name: build
          path: client/build/

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: build
          path: client/build/

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact_name: build

